title: Junghwan (Steve) Kim
description: Thoughts, ideas, and explorations
url: "https://baobabtr33.github.io"
baseurl: "/blog"

# Build settings
markdown: kramdown

# Exclude files
exclude:
  - README.md
